baseURL = "https://asarmakeeva.com/"
languageCode = "en-us"
title = "Anastasiia Sarmakeeva"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Hi, I’m Anastasiia"
Content = """
Machine Learning Engineer (PhD) working on computer vision, synthetic data, and reproducible ML.

I’ve worked on large-scale medical imaging datasets at the FDA and publish open-source research in machine learning, computer vision and compuataional fluid dynamic simulation field.
"""

[params]
  ShowReadingTime = true
  ShowShareButtons = false

# What sections appear on the home list
mainSections = ["posts"]

[[menu.main]]
  name = "Bio"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 4

